### PR TITLE
fix missing module imports

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by maximecb** [comment]
I'd like a bit of a justification for these kinds of changes?

**Comment by maximecb** [comment]
This does not improve code clarity, for instance:

-        assert (runtime.gc.inFromSpace(vm, ptr));
+        import runtime.gc : inFromSpace;
+        assert (inFromSpace(vm, ptr));

I'm assuming you're making these changes so that some tool can digest the code better...? Code clarity wins for me.

**Comment by MartinNowak** [comment]
Those were the places affected by an upcoming fix of [Issue 313 - [module] Fully qualified names bypass private imports](https://issues.dlang.org/show_bug.cgi?id=313) and [Issue 314 - [module] Static, renamed, and selective imports are always public](https://issues.dlang.org/show_bug.cgi?id=314).
In most most cases some symbol was used via FQN even though the corresponding module wasn't imported.

> This does not improve code clarity, for instance

I could as well just `import runtime.gc;`  and keep the FQN.

**Comment by maximecb** [comment]
Ok. I would prefer that.

I take it this kind of fully qualified name reference is becoming illegal in the next DMD?

**Comment by MartinNowak** [comment]
Updated.

> I take it this kind of fully qualified name reference is becoming illegal in the next DMD?

It's one of the longstanding bugs in dmd's import system.
I hope we can finally fix it for 2.068.0 (end of may) given that we don't hit too much resistance.

**Pull request merged**
