### PR TITLE
Add Array.of method

### PR DESCRIPTION
**Pull request by pselle**
Referencing #179, adds Array.of method

This is my first PR to this project, so please let me know how to improve this! This adds the Array.of method and a test for it where it appeared to make sense to do so.

### CODE REVIEW

**Comment by maximecb** [comment]
Thanks for contributing :)

In terms of improvements, I would suggest testing corner cases like calling the method with zero or one element.

Also, we're going away from

```js
    if(!array_eq(Array.of(2,3), [2,3]))
        return 1;
```

In favor of:

```js
assert (array_eq(Array.of(2,3), [2,3]))
```

The return codes date back to a time where Higgs didn't yet have support for exceptions.

**Comment by pselle** [comment]
Thanks for the feedback! Updated.

**Comment by maximecb** [comment]
Merged. Sorry for not responding faster, I'm at ECOOP and it's taking most of my time! Thanks for contributing :)

**Comment by pselle** [comment]
YAYY No worries, thanks for checking it out! :tada:

**Pull request merged**
