### PR TITLE
use Travis-CI's D support

### PR DESCRIPTION
**Pull request by MartinNowak**
- uses latest dmd by default

### CODE REVIEW

**Comment by maximecb** [comment]
The travis CI build seems to fail for some odd reason.

**Comment by MartinNowak** [comment]
I overlooked that you actually installed time.
Maybe there is something that could be used instead given that installing time requires sudo + apt-get and ~8s.
https://travis-ci.org/higgsjs/Higgs/builds/46021027#L110

**Comment by tach4n** [comment]
time is just used to time the testrunner itself, which is nice but not too necessary. Some suggestions/options:

 - remove it, let the dev run it locally when they want
 - have another target the dev can call locally when they want to call time
 - get a lil fancy and check envars to see if we're in a travis environment and not call time in that case

**Comment by MartinNowak** [comment]
I replaced it with a time output in the test-runner which is more relevant than the unittests anyhow.

**Comment by maximecb** [comment]
The total test time is actually a useful quantity to have, I'd rather we keep that.

Also. Something seems broken in the test runner. It says 0 tests run.

We should probably add an assertion to check that the number of tests passed is greater than zero.

**Comment by tach4n** [comment]
Yes , the test-runner should check that the tests run/passed is greater than zero and bail in that case just as if there are failures, printing an error might be good too.

That stuff seems unrelated to the intent of the PR though, not sure how you want to handle it.

**Comment by MartinNowak** [comment]
The docker containers use XFS or some other filesystem that doesn't support d_type in dirent, therefor the directory traversal fails. One would need to call stat to find out whether something is a dir or a file.
http://nerdfortress.com/2008/09/19/linux-xfs-does-not-support-direntd_type/

For the time being I left away the `sudo: false` and it will get tested in VirtualBox.

**Comment by maximecb** [comment]
Can you explain why this worked before and not now?

**Comment by MartinNowak** [comment]
> Can you explain what the sudo: false flag is?

If your test-suite doesn't need root rights (e.g. to install something) then it can run on docker instead of virtualbox, saving lots of resources.
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by MartinNowak** [comment]
Anything left to do?

**Pull request merged**
