### PR TITLE
fix deprecations with newer compilers

### PR DESCRIPTION
**Pull request by MartinNowak**
- explicit switch fall-through
- replace currAppTick
- disable module cycle detection

### CODE REVIEW

**Comment by bFraley** [comment]
@MartinNowak Thank you so much for tending to this! I'm hoping @maximecb can take a quick look and give her approval to merge.

**Comment by maximecb** [comment]
@MartinNowak Is it no longer possible to get a microsecond timer? If so, that's unfortunate, because a millisecond timer will likely not be precise enough :\

**Comment by wilzbach** [comment]
> @MartinNowak Is it no longer possible to get a microsecond timer? If so, that's unfortunate, because a millisecond timer will likely not be precise enough :\

I think you can do `total!"usecs"` and even `total!"hnsecs"` as `Duration` is internally kept as `hnsecs`.
@MartinNowak just removed your function because it was unused.

**Comment by MartinNowak** [comment]
Yes, [MonoTime](https://dlang.org/library/core/time/mono_time_impl.html) internally uses whatever high-precision timer is available.
It's no longer possible to get a high-precision time since app start.

**Pull request merged**
